// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frames streamed to the frontend while a reply is being generated.
 */
export type AiDelta = { "kind": "text", "data": { text: string, } } | { "kind": "toolCall", "data": { id: string, name: string, input: string, } } | { "kind": "toolResult", "data": { id: string, ok: boolean, summary: string, } } | { "kind": "done" } | { "kind": "error", "data": { message: string, } };
