// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in an environment's variable set.
 *
 * `id` is a stable identifier, independent of `key` — it is what
 * [`SecretStore`](devos_secrets::SecretStore) vault entries for `secret`
 * variables are keyed by (see [`ApiEnvironment`]'s doc comment), so
 * renaming `key` never orphans a vault entry. Assigned once, on first
 * save; a var arriving with an empty `id` (a brand-new row from the
 * editor) gets one generated for it.
 */
export type ApiEnvVar = { id: string, key: string, value: string, secret: boolean, };
