// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiEnvVar } from "./ApiEnvVar";

/**
 * A named set of variables (`API_URL`, `TOKEN`, …) that [`substitute_spec`]
 * resolves `{{KEY}}` placeholders against. At most one environment is
 * `active` at a time; `api_send` resolves against whichever one is.
 *
 * **`ApiEnvVar::secret` is backed by the secrets vault (SEC-105).** A
 * variable marked secret has its value encrypted via
 * `devos_secrets::SecretStore` under `api-env-var:{ApiEnvVar::id}` — the
 * `api_environments.vars` JSON blob stores an empty string for it, never
 * the plaintext. `repo::hydrate` fills the real value back in on every
 * read (`list_environments`, `active_environment`, and the environment
 * returned from `create_environment`/`update_environment`), so the editor
 * and `api_send`'s `{{VAR}}` substitution see it exactly as before —
 * only at-rest storage changed. A variable that is not secret is still
 * plain JSON, same as `api_requests.headers`.
 */
export type ApiEnvironment = { id: string, name: string, vars: Array<ApiEnvVar>, active: boolean, updatedAt: number, };
