// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiEnvVar } from "./ApiEnvVar";

/**
 * A named set of variables (`API_URL`, `TOKEN`, …) that [`substitute_spec`]
 * resolves `{{KEY}}` placeholders against. At most one environment is
 * `active` at a time; `api_send` resolves against whichever one is.
 *
 * **`ApiEnvVar::secret` is not yet backed by the secrets vault.** Every
 * variable, "secret" or not, is stored as plain JSON in `api_environments`
 * — the same place `api_requests.headers` already stores plaintext, a gap
 * this module's own SEC-105 finding already named. Marking a variable
 * secret today buys UI masking only (the value is hidden by default in the
 * editor); it does not encrypt anything, and it does not stop the value
 * from reaching an AI provider if it is later substituted into a request
 * whose contents get shared with a model. Routing secret values through
 * `devos-secrets` instead is real future work, not something this flag
 * should be read as already doing.
 */
export type ApiEnvironment = { id: string, name: string, vars: Array<ApiEnvVar>, active: boolean, updatedAt: number, };
