// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in an environment's variable set. `secret` is a display hint
 * only — see the doc comment on [`ApiEnvironment`] for what that does and
 * does not mean today.
 */
export type ApiEnvVar = { key: string, value: string, secret: boolean, };
