// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiHistoryEntry = { id: string, method: string, url: string, status: number, durationMs: number, sentAt: number, };
