// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiHeader } from "./ApiHeader";

export type ApiResponse = { status: number, headers: Array<ApiHeader>, body: string, truncated: boolean, durationMs: number, sizeBytes: number, };
