// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiHeader } from "./ApiHeader";

export type ApiRequestSpec = { method: string, url: string, headers: Array<ApiHeader>, body: string | null, };
