// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One appended row of the audit log. See [`crate::audit`] for what is
 * recorded and — more importantly — what deliberately is not.
 */
export type AuditEntry = { id: number, 
/**
 * "user" | "ai" | "system"
 */
actor: string, 
/**
 * Stable dotted event type, e.g. `ai.tool.denied`. The outcome is part
 * of the identifier so the UI never parses prose to find one.
 */
action: string, detail: string | null, createdAt: number, };
