// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEntry } from "./AuditEntry";

/**
 * The audit log as one screen sees it: the newest entries, plus the numbers
 * that let the page state its own retention honestly instead of implying the
 * list is everything that ever happened.
 */
export type AuditLog = { entries: Array<AuditEntry>, 
/**
 * Rows in the table, which may exceed `entries.len()`.
 */
total: number, 
/**
 * Timestamp of the oldest surviving row — how far back the record
 * actually reaches, which is not the same as the retention window on a
 * fresh install.
 */
oldest: number | null, 
/**
 * Days kept, from [`crate::audit::RETENTION_DAYS`]. Sent rather than
 * duplicated in TypeScript so the screen cannot promise a window the
 * backend does not keep.
 */
retentionDays: number, };
