// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupKind } from "./BackupKind";

/**
 * One file in `backups/`, with the metadata needed to choose between them.
 */
export type BackupEntry = { name: string, 
/**
 * Absolute, so the UI can hand it straight to "reveal in Explorer".
 */
path: string, kind: BackupKind, 
/**
 * Modification time in epoch milliseconds.
 *
 * Read from the filesystem rather than parsed out of the file name: the
 * daily name only carries a calendar date, and a name is a claim while
 * `mtime` is a fact. `0` when the platform will not report one.
 */
modifiedAt: number, size: number, };
