// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which trigger wrote a backup — the difference matters when choosing one.
 *
 * `Unknown` is not a failure. The backup directory is an ordinary folder and
 * someone can legitimately drop a file into it (copied off another machine,
 * or renamed by hand); refusing to list it would make the folder and the UI
 * disagree, and validation is what decides whether a file is usable anyway.
 */
export type BackupKind = "daily" | "preMigration" | "replaced" | "unknown";
