// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupEntry } from "./BackupEntry";
import type { PendingRestore } from "./PendingRestore";

/**
 * Everything the backups UI needs in one round trip: where the folder is,
 * what is in it, and whether a restore is already waiting for a restart.
 */
export type BackupListing = { dir: string, entries: Array<BackupEntry>, pending: PendingRestore | null, };
