// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { id: string, conversationId: string, 
/**
 * "user" | "assistant"
 */
role: string, content: string, createdAt: number, };
