// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A palette-invokable command contributed by a module (or later, a plugin).
 */
export type CommandDescriptor = { id: string, module: string, title: string, keywords: Array<string>, shortcut: string | null, };
