// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeProject } from "./ComposeProject";
import type { ComposeServiceStatus } from "./ComposeServiceStatus";

export type ComposeStatus = { project: ComposeProject, services: Array<ComposeServiceStatus>, };
