// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerContainer } from "./DockerContainer";

export type ComposeServiceStatus = { service: string, 
/**
 * `None` when this service is declared in the compose file but nothing
 * has ever been started for it — a real, common state (a fresh clone
 * before the first `up`), not an error.
 */
container: DockerContainer | null, };
