// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComposeProject = { file: string, 
/**
 * The `-p`/`--project-name` Compose derives when nothing overrides it:
 * the compose file's own directory name, lowercased and sanitized —
 * the same value the `com.docker.compose.project` label carries, which
 * is how a running container is matched back to this file.
 */
name: string, services: Array<string>, };
