// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three-way content of a conflicted file, read from git's index
 * stages 1/2/3. `None` for a side with no version at that stage — the
 * base is absent when both sides added the file independently; `ours`
 * or `theirs` is absent when that side deleted it.
 */
export type ConflictSides = { base: string | null, ours: string | null, theirs: string | null, };
