// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Conversation = { id: string, title: string, provider: string, model: string, createdAt: number, updatedAt: number, };
