// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbConnection = { id: string, name: string, driver: string, path: string, createdAt: number, };
