// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbColumn = { name: string, dataType: string, notNull: boolean, primaryKey: boolean, defaultValue: string | null, };
