// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbColumn } from "./DbColumn";

export type DbTable = { name: string, kind: string, rowCount: number, columns: Array<DbColumn>, };
