// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyStatus } from "./DependencyStatus";

export type DependencyCheck = { ecosystem: string, status: DependencyStatus, vulnerabilityCount: number | null, detail: string | null, };
