// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeployProject = { id: string, name: string, framework: string | null, updatedAt: number, };
