// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Deployment = { id: string, name: string, url: string, state: string, target: string | null, createdAt: number, commitMessage: string | null, };
