// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerContainer = { id: string, name: string, image: string, 
/**
 * "running" | "exited" | "paused" | …
 */
state: string, 
/**
 * Human status, e.g. "Up 2 hours".
 */
status: string, 
/**
 * Rendered port mappings, e.g. "0.0.0.0:8080→80/tcp".
 */
ports: Array<string>, created: number, };
