// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerRootStatus } from "./DockerRootStatus";

export type DockerRootCheck = { status: DockerRootStatus, containers: Array<string>, };
