// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text preview of a project file (file explorer).
 */
export type FilePreview = { content: string, truncated: boolean, binary: boolean, size: number, };
