// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitCommit = { id: string, shortId: string, author: string, 
/**
 * Unix seconds.
 */
time: number, summary: string, };
