// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry from `git status --porcelain=v2 -z`.
 */
export type GitFileEntry = { path: string, 
/**
 * Original path for renames.
 */
origPath: string | null, 
/**
 * Index (staged) status letter: M A D R C . etc.
 */
staged: string, 
/**
 * Worktree (unstaged) status letter.
 */
unstaged: string, untracked: boolean, conflicted: boolean, };
