// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitRepoInfo = { isRepo: boolean, branch: string | null, upstream: string | null, ahead: bigint, behind: bigint, };
