// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileEntry } from "./GitFileEntry";
import type { GitRepoInfo } from "./GitRepoInfo";

/**
 * Combined payload for the git page: one IPC round trip per refresh.
 */
export type GitStatus = { info: GitRepoInfo, entries: Array<GitFileEntry>, };
