// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistorySecretFinding } from "./HistorySecretFinding";
import type { HistorySecretScanStatus } from "./HistorySecretScanStatus";

export type HistorySecretScan = { status: HistorySecretScanStatus, commitsScanned: number, findings: Array<HistorySecretFinding>, detail: string | null, };
