// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistorySecretFinding = { 
/**
 * Short (7-character) commit hash — enough to `git show`/`git log` it,
 * short enough to display in a list.
 */
commit: string, file: string, kind: string, };
