// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One content-search hit, UI-facing (see `search` for the internal type).
 */
export type IndexHit = { file: string, startLine: number, snippet: string, };
