// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";

export type JobInfo = { id: string, module: string, kind: string, status: JobStatus, error: string | null, createdAt: number, startedAt: number | null, finishedAt: number | null, };
