// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobInfo } from "./JobInfo";
import type { NotificationDto } from "./NotificationDto";

/**
 * Events broadcast on the kernel event bus and forwarded to the frontend
 * on the `devos://event` channel.
 */
export type KernelEvent = { "kind": "workspacesChanged" } | { "kind": "projectsChanged", "data": { workspaceId: string, } } | { "kind": "settingsChanged", "data": { key: string, } } | { "kind": "jobUpdated", "data": { job: JobInfo, } } | { "kind": "notificationAdded", "data": { notification: NotificationDto, } };
