// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured server: how to start it, not whether it is currently
 * running — see the module doc comment on why connections are one-shot.
 */
export type McpServer = { id: string, name: string, command: string, args: Array<string>, createdAt: number, };
