// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool a server advertised via `tools/list`. `input_schema` is passed
 * through verbatim — it is the server's own JSON Schema, not something this
 * module interprets.
 */
export type McpTool = { name: string, description: string | null, inputSchema: unknown, };
