// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of fact a memory entry records. Four categories named by the
 * roadmap this shipped against, plus `Other` for anything that predates
 * categorization (the migration backfills every existing row to it) or that
 * a caller genuinely can't place.
 */
export type MemoryCategory = "architecture" | "convention" | "decision" | "known-issue" | "other";
