// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryCategory } from "./MemoryCategory";

/**
 * One saved long-term memory fact, scoped to a project. Always visible and
 * deletable in the UI — memory is transparent, not magic.
 */
export type MemoryEntry = { id: string, project: string, content: string, category: MemoryCategory, createdAt: number, };
