// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Monitor } from "./Monitor";
import type { MonitorCheck } from "./MonitorCheck";

export type MonitorStatus = { monitor: Monitor, lastCheck: MonitorCheck | null, uptimePct: number, avgMs: number, recent: Array<MonitorCheck>, };
