// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Monitor = { id: string, name: string, url: string, intervalSecs: number, enabled: boolean, createdAt: number, };
