// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MonitorCheck = { id: string, monitorId: string, status: number | null, ok: boolean, durationMs: number, error: string | null, checkedAt: number, };
