// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationDto = { id: string, module: string, 
/**
 * "info" | "warning" | "error"
 */
level: string, title: string, body: string | null, read: boolean, createdAt: number, };
