// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutdatedStatus } from "./OutdatedStatus";

export type OutdatedCheck = { ecosystem: string, status: OutdatedStatus, outdatedCount: number | null, detail: string | null, };
