// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A restore that has been staged and will apply on the next boot.
 *
 * Doubles as the on-disk marker (`restore-pending/RESTORE.json`): the record
 * the UI shows and the record boot acts on are the same bytes, so they cannot
 * describe different things.
 */
export type PendingRestore = { 
/**
 * File name of the backup that will be installed.
 */
source: string, requestedAt: number, size: number, };
