// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryResult = { columns: Array<string>, rows: Array<Array<string | null>>, rowCount: number, rowsAffected: number, durationMs: number, truncated: boolean, readOnly: boolean, };
