// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a rebase is currently paused mid-flight, and how far through
 * it. Detected from `.git/rebase-merge` or `.git/rebase-apply` — see
 * [`crate::ops::rebase_status`].
 */
export type RebaseStatus = { inProgress: boolean, step: number | null, total: number | null, branch: string | null, };
