// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretFinding } from "./SecretFinding";

export type SecretScan = { filesScanned: number, findings: Array<SecretFinding>, };
