// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyCheck } from "./DependencyCheck";
import type { DockerRootCheck } from "./DockerRootCheck";
import type { EnvFileCheck } from "./EnvFileCheck";
import type { GitCheck } from "./GitCheck";
import type { HistorySecretScan } from "./HistorySecretScan";
import type { OutdatedCheck } from "./OutdatedCheck";
import type { SecretScan } from "./SecretScan";

export type SecurityReport = { git: GitCheck, secrets: SecretScan, historySecrets: HistorySecretScan, envFiles: EnvFileCheck, dockerRoot: DockerRootCheck, dependencies: Array<DependencyCheck>, outdated: Array<OutdatedCheck>, };
