// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyCheck } from "./DependencyCheck";
import type { GitCheck } from "./GitCheck";
import type { SecretScan } from "./SecretScan";

export type SecurityReport = { git: GitCheck, secrets: SecretScan, dependencies: Array<DependencyCheck>, };
