// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Snippet = { id: string, title: string, language: string, body: string, tags: Array<string>, createdAt: number, updatedAt: number, };
