// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnippetDraft = { id: string | null, title: string, language: string, body: string, tags: Array<string>, };
