// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One "go to symbol" match: a declaration site, not a chunk excerpt. See
 * [`indexer::find_symbols`].
 */
export type SymbolHit = { name: string, kind: string, file: string, startLine: number, };
