// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemHistoryPoint = { ts: number, cpuUsage: number, memUsed: number, memTotal: number, };
