// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskInfo } from "./DiskInfo";
import type { ProcessInfo } from "./ProcessInfo";

export type SystemSnapshot = { cpuUsage: number, cpuCores: number, memTotal: number, memUsed: number, swapTotal: number, swapUsed: number, uptimeSecs: number, disks: Array<DiskInfo>, topProcesses: Array<ProcessInfo>, };
