// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frames streamed to the frontend on a per-session Tauri channel.
 */
export type TermEvent = { "kind": "output", "data": { bytes: Array<number>, } } | { "kind": "exit", "data": { code: number | null, } };
